name: Cinema-env
channels:
  - conda-forge
dependencies:
  - numpy
  - vtk
  - meshio
  - matplotlib
  - pyqt
  - itkwidgets>=0.25.2
  - pip
  - panel
  - ipygany
  - ipyvtklink
  - pip:
      - pytest-memprof