#!/usr/bin/env python3

import matplotlib.pyplot as plt
import h5py
import argparse
from Cinema.Prompt import plotStyle

def plot1d(h5file, xlog=False , ylog=True, 
           err=False, save=False, show=True,
           xlabel='x', ylabel='y', title='title'):

    h5f = h5py.File(f'{h5file}')

    if 'center' not in h5f:
        raise ValueError("Only 1d scorer for now, or may be not a Prompt h5 file.")

    x = h5f[f'center'][()]
    y = h5f[f'weight'][()]
    e = h5f[f'sdev'][()]

    if not err:
        plt.plot(x[:-1], y)
    else:
        plt.errorbar(x[:-1],y,e)

    plt.xlabel(xlabel)
    plt.ylabel(ylabel)
    plt.title(title)

    if xlog:
        plt.xscale('log')
    if ylog:
        plt.yscale('log')
    if show:
        plt.show()
    if save:
        plt.savefig(f'{h5file}.pdf')
    if not show and not save:
        raise ValueError("Nothing happens: plot does not showed and not saved.")
    
def parse():
    parser = argparse.ArgumentParser()
    parser.add_argument('h5file', type=str, help='Path of h5 file produced by Prompt simulations.')
    parser.add_argument('--save', action='store_true', help='save plot as pdf file.')
    parser.add_argument('--show', action='store_true', help='show plot.')
    parser.add_argument('--xlog', action='store_true', help='xlog scale.')
    parser.add_argument('--ylog', action='store_true', help='ylog scale.')
    parser.add_argument('--xlabel', type=str, default='x', help='xlabel.')
    parser.add_argument('--ylabel', type=str, default='y', help='ylabel.')
    parser.add_argument('--title', type=str, default='title', help='title.')
    parser.add_argument('--err', action='store_true', help='err bar.')
    args = parser.parse_args()
    return args

def main():
    plotStyle()
    args = parse()
    plot1d(args.h5file, args.xlog, args.ylog, args.err, args.save, args.show, 
           args.xlabel, args.ylabel, args.title)

if __name__ == '__main__':
    main()